name: Build Linux
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.xml'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter channel dev
      - run: flutter config --enable-linux-desktop
      - run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev -y
      - run: flutter build linux --debug
      - name: Generate Localization
        run: dart bin/locale_gen.dart assets/locales lib/internal/locales
      - run: git config --global user.name "dahliaOS" && git commit -am "Generated Locales" && git push
        name: Push Localization
      - name: Upload linux build for build_linux
        uses: actions/upload-artifact@v2
        with:
          name: pangolin-linux-builds
          path: build/linux/debug/pangolin_desktop
