name: Locale Generator
on:
  push:
    paths:
      - '**.xml'
    branches: [ master ]
jobs:
  locale_gen:
    name: Generate Locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Flutter SDK
        uses: subosito/flutter-action@v1
      - run: flutter channel dev
      - run: flutter pub get
      - run: dart bin/locale_gen.dart assets/locales lib/internal/locales
      - run: git config --global user.name "dahliaOS" && git commit -am "Generated Locales" && git push
