name: Locale Generator
on:
  push:
    paths:
      #- '**.xml'
      - "**.xml.void"
    branches: [ master ]
jobs:
  locale_gen:
    name: Generate Locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Flutter SDK
        uses: subosito/flutter-action@v1
      - run: flutter channel dev
      - run: flutter pub get
