name: Locale Generator
on:
  push:
    paths:
      - '**.xml'
    branches: [ master ]
jobs:
  locale_gen:
    name: Generate Locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter channel dev
      - run: flutter upgrade
      - run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev -y
      - run: dart bin/locale_gen.dart assets/locales lib/internal/locales
      - run: git config --global user.name "dahliaOS" && git commit -am "Generated Locales" && git push
