name: Update Submodules

on: [repository_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update Submodules
        run: |
          git submodule update --recursive --remote
      - name: Push Changes
        run: |
          git add . \
          && git config --global user.email "update-submodules@dahliaos.io" \
          && git config --global user.name "dahliaOS Bot" \
          && git commit -m "Update Submodules" \
          && git push
