on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: subosito/flutter-action@v1
    - run: flutter channel master
    - run: flutter config --enable-web
    - run: flutter build web
    - run: git config --global user.name "dahliaOS" && git commit -a -m "You've found me!"
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{secrets.FTP_HOST}}/public_html/web_build
        ftp-username: ${{secrets.FTP_USERNAME}}
        ftp-password: ${{secrets.FTP_PASSWORD}}
        local-dir: build/web/
