name: Build and deploy web
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_deploy_web:
    name: Build and deploy web
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: subosito/flutter-action@v1
    - run: flutter channel dev
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Prepare to deploy
      run: git config --global user.name "dahliaOS" && git commit -a -m "You've found me!"
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{secrets.FTP_HOST}}/web_build/
        ftp-username: ${{secrets.FTP_USERNAME}}
        ftp-password: ${{secrets.FTP_PASSWORD}}
        local-dir: build/web/
