name: Build and Deploy Web
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.xml'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_deploy_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: subosito/flutter-action@v1
    - run: flutter channel dev
    - name: Clone existing files
      run: git clone "${{ secrets.GIT_WEB_REMOTE }}" build/webout
    - run: flutter config --enable-web
    - run: dart bin/locale_gen.dart assets/locales lib/internal/locales
      name: Generate Localization
    - run: flutter build web
    - name: Deploy
      run: |
        cd build/webout
        rm -r *
        cp -r ../web/* .
        git config --global user.name dahliaOS-WebBuild
        git config --global user.email build@web.dahliaos.io
        git add -A
        git commit -m "Update $(date)"
        git push --set-upstream origin master --force
    - run: git config --global user.name "dahliaOS" && git commit -am "Generated Locales" && git push
      name: Push Localization