name: Build and Deploy Web
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_deploy_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: subosito/flutter-action@v1
    - run: flutter channel dev
    - name: Clone existing files
      run: git clone "${{ secrets.GIT_WEB_REMOTE }}" build/web
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Deploy
      run: |
        cd build/web
        git add .
        git commit -m "Update $(date)"
        git push --set-upstream origin master --force
